<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<div></div>
	<div></div>
	<div></div>
	<div></div>
	<div></div>
	<div></div>
	<div></div>
	<div></div>
	<div></div>
	<script>
		// --------------------------Promise.reject() ----------------------------
		// Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。
		// const p = Promise.reject('出错了');
		// 等同于
		const p = new Promise((resolve, reject) => reject('出错了'));
		p.then(null, function(s) {
			console.log(s);
		});
		// 出错了

		// 上面代码生成一个Promise对象的实例p,状态为rejected,回调函数会立即执行。
		// 出错了

		// 注意，Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。这一点与Promise.resolve方法不一致。
		const thenable = {
			then(resolve, reject) {
				reject('出错了');
			}
		};
		Promise.reject(thenable)
		.catch(e => {
			console.log(e === thenable);
		})
		// true
 	</script>
</body>
</html>